### ISSUE TITLE
login and auth through microsoft auth

### ISSUE THREAD

**Issue by Nayana278820** [hack4impact-utk/uw-grant-management#2]
- Frontend → actual button / redirecting to map page
- Backend → Authorization so that only United Way emails can access

**Comment by zac-perry** [comment]
Update: Looks like for Nextjs, **[NextAuth](https://next-auth.js.org)** is pretty widely used for implementing authorization through different providers (Google, Microsoft, Github, etc.). NextAuth also provides support for JWTs, cookies / caching, session management, etc.

For Microsoft authentication, it looks like we could use the **[Azure Active Directory Provider](https://next-auth.js.org/providers/azure-ad)**. This does require registering the app on Azure and setting up a Tenant Configuration. Setting up this configuration will allow us to specify what domains are able to sign in through the app. So, we could restrict access to only allow United Way email addresses / domains to access & sign in.

Here's a small demo using the Azure AD provider. In this example, the authentication is configured to only allow UTK email domains just for simplicity sake.
![AuthDemo](https://github.com/hack4impact-utk/uw-grant-management/assets/97002490/954867c1-bbab-4149-9219-dfd5f99b7fb8)
