### ISSUE TITLE
Create horizontal bar charts for different demographical distributions

### ISSUE THREAD

**Issue by LakelonBailey** [hack4impact-utk/uw-grant-management#59]
# Create horizontal bar charts for different demographical distributions

## Example:
![image](https://github.com/hack4impact-utk/uw-grant-management/assets/102266508/ad6a0698-7a9f-4084-8abc-83e06256900f)

## Demographics to use

For now, please create a horizontal bar chart for clients served distribution in age, sex, ethnicity, race, and household income.

**Comment by maddyyu** [comment]
# 4/14 Update

- implemented the chart, but all bars are on one chart 
- for next week make sure the bars are separated 
- make datasets separate to ensure there's no overlap between categories like age, sex, ethnicity, race and household
<img width="1290" alt="Screenshot 2024-04-14 at 4 09 03 PM" src="https://github.com/hack4impact-utk/uw-grant-management/assets/127363085/0a6f9fb4-3c01-4bb8-8faa-d2bee16d31b2">
